spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: yyyy-MM-dd
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework: info
    com:
      niksan:
        springboot:
          myfirstwebapp: debug