spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: yyyy-MM-dd
  datasource:
    url: jdbc:mysql://localhost:3306/todos
    username: todos-user
    password: dummytodos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    org:
      springframework: info
    com:
      niksan:
        springboot:
          myfirstwebapp: debug